import type { LucideIcon } from "lucide-react";
import {
  Archive,
  AtSign,
  Atom,
  AudioLines,
  Bell,
  Book,
  BookMarked,
  BookOpen,
  Bookmark,
  Brain,
  Briefcase,
  Building2,
  Calendar,
  CalendarDays,
  Camera,
  Check,
  CheckCheck,
  Circle,
  Clipboard,
  ClipboardList,
  Clock,
  Cloud,
  Coffee,
  Columns3,
  Compass,
  Database,
  Eye,
  Feather,
  File,
  FilePlus,
  FileText,
  Files,
  Flag,
  Flame,
  FlaskConical,
  Flower2,
  Folder,
  FolderOpen,
  GalleryHorizontal,
  Gem,
  Gift,
  GitBranch,
  Globe,
  GraduationCap,
  Handshake,
  Hash,
  Heart,
  Hexagon,
  Home,
  Hourglass,
  Image,
  Inbox,
  Infinity as InfinityIcon,
  Kanban,
  Key,
  Landmark,
  Layers,
  LayoutGrid,
  Leaf,
  Library,
  Lightbulb,
  Link2,
  List,
  ListOrdered,
  ListTodo,
  Lock,
  Mail,
  Map,
  MapPin,
  MessageCircle,
  MessageSquare,
  Mic,
  Moon,
  Mountain,
  Music,
  Network,
  Newspaper,
  Notebook,
  NotebookPen,
  Package,
  Paperclip,
  PenLine,
  Pencil,
  Pin,
  Puzzle,
  Quote,
  Rocket,
  ScrollText,
  Search,
  Send,
  Settings,
  Shield,
  Sparkles,
  Square,
  Star,
  StickyNote,
  Sun,
  Sunrise,
  Table2,
  Tag,
  Tags,
  Target,
  Tent,
  Timer,
  Triangle,
  Trophy,
  Type,
  User,
  UserRound,
  Users,
  Video,
  Volume2,
  Workflow,
  Zap,
} from "lucide-react";

/** Frontmatter value: `lucide:file-text`. Emoji and short marks stay unprefixed. */
export const LUCIDE_PREFIX = "lucide:";

export function isLucideIcon(icon?: string): boolean {
  return Boolean(icon?.startsWith(LUCIDE_PREFIX));
}

export function toKebab(name: string): string {
  return name
    .trim()
    .replace(/^lucide:/i, "")
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[\s_]+/g, "-")
    .toLowerCase();
}

export function lucideIconName(icon: string): string {
  return toKebab(icon.startsWith(LUCIDE_PREFIX) ? icon.slice(LUCIDE_PREFIX.length) : icon);
}

export function lucideIconValue(name: string): string {
  return `${LUCIDE_PREFIX}${toKebab(name)}`;
}

export const PAGE_ICONS: Record<string, LucideIcon> = {
  file: File,
  "file-text": FileText,
  "file-plus": FilePlus,
  files: Files,
  folder: Folder,
  "folder-open": FolderOpen,
  archive: Archive,
  clipboard: Clipboard,
  "clipboard-list": ClipboardList,
  "sticky-note": StickyNote,
  notebook: Notebook,
  "notebook-pen": NotebookPen,
  book: Book,
  "book-open": BookOpen,
  "book-marked": BookMarked,
  library: Library,
  "scroll-text": ScrollText,
  newspaper: Newspaper,
  star: Star,
  sparkles: Sparkles,
  bookmark: Bookmark,
  heart: Heart,
  flag: Flag,
  pin: Pin,
  tag: Tag,
  tags: Tags,
  hash: Hash,
  "at-sign": AtSign,
  "link-2": Link2,
  paperclip: Paperclip,
  calendar: Calendar,
  "calendar-days": CalendarDays,
  clock: Clock,
  timer: Timer,
  hourglass: Hourglass,
  sunrise: Sunrise,
  moon: Moon,
  sun: Sun,
  user: User,
  users: Users,
  "user-round": UserRound,
  handshake: Handshake,
  "graduation-cap": GraduationCap,
  home: Home,
  map: Map,
  "map-pin": MapPin,
  globe: Globe,
  compass: Compass,
  "building-2": Building2,
  landmark: Landmark,
  tent: Tent,
  briefcase: Briefcase,
  target: Target,
  check: Check,
  "check-check": CheckCheck,
  "list-todo": ListTodo,
  list: List,
  "list-ordered": ListOrdered,
  kanban: Kanban,
  "layout-grid": LayoutGrid,
  "columns-3": Columns3,
  "table-2": Table2,
  "gallery-horizontal": GalleryHorizontal,
  database: Database,
  workflow: Workflow,
  "git-branch": GitBranch,
  network: Network,
  image: Image,
  camera: Camera,
  music: Music,
  mic: Mic,
  "audio-lines": AudioLines,
  "volume-2": Volume2,
  video: Video,
  pencil: Pencil,
  "pen-line": PenLine,
  type: Type,
  quote: Quote,
  "message-square": MessageSquare,
  "message-circle": MessageCircle,
  mail: Mail,
  inbox: Inbox,
  send: Send,
  feather: Feather,
  lightbulb: Lightbulb,
  flame: Flame,
  zap: Zap,
  atom: Atom,
  "flask-conical": FlaskConical,
  leaf: Leaf,
  "flower-2": Flower2,
  mountain: Mountain,
  cloud: Cloud,
  brain: Brain,
  rocket: Rocket,
  key: Key,
  lock: Lock,
  shield: Shield,
  settings: Settings,
  puzzle: Puzzle,
  trophy: Trophy,
  gem: Gem,
  gift: Gift,
  search: Search,
  eye: Eye,
  bell: Bell,
  layers: Layers,
  package: Package,
  coffee: Coffee,
  infinity: InfinityIcon,
  circle: Circle,
  square: Square,
  triangle: Triangle,
  hexagon: Hexagon,
};

export const PAGE_ICON_NAMES = Object.keys(PAGE_ICONS);

export function lookupPageIcon(name: string): LucideIcon | undefined {
  return PAGE_ICONS[toKebab(name)];
}

export function filterPageIcons(query: string): string[] {
  const q = toKebab(query);
  if (!q) return PAGE_ICON_NAMES;
  const compact = q.replace(/-/g, "");
  return PAGE_ICON_NAMES.filter((n) => n.includes(q) || n.replace(/-/g, "").includes(compact));
}
